[site]
# The title of the site
title = "SilverHalide"
# The name of the author
author = "Rohit"
description = "Here I post the images I make. almost complete rolls, without curation. Mostly Analog, Largely DIY, Still Learning #filmisnotdead"

# Site navigation links
# You can remove any navigation links or add more link by adding following lines
#     [[site.nav]]
#     icon = ""
#     link = ""
# Navigation links are added in the order encountered.

[[site.nav]]
icon = "assets/icons/home.svg"
link = "https://blog.kernelanxiety.dev"

[[site.nav]]
icon = "assets/icons/instagram.svg"
link = "https://instagram.com/rohitshetty00"

[[site.nav]]
icon = "assets/icons/pixelfed.svg"
link = "https://pixelfed.social/rohitshetty"

[[site.nav]]
icon = "assets/icons/mastodon.svg"
link = "https://hachyderm.io/@rohit"



# Setttings for photo size
[image]
# Width for thumbnail images
thumbnailWidth = 640
# Width for enlarged images
originalWidth = 2048

# Layout for grids
[layout]
minColumn = 1
maxColumn = 4
minWidth = 200

# Photo sections
# You can remove or add more sections by adding following lines
#     [[section]]
#     title = "section title"
#     text = "section description"
#     slug = "section-slug"
#     folder = "folder of photos"
#     ascending = false
# Photo sections are added in the order encountered.


[[section]]
title = "2023 W48-W49"
text = "<p>I experimented with pushing film for the first time. This made shooting in low/difficult light conditions a bit easier. I have seen experiments where people pushed Kentmere400 to 1600, but I think this will be the most I'll push this film.</p><p>Most of my images are in the 1/15-1/60 shutter speed range, resulting in a blurry or non-sharp look that I don't like in most cases, but it works for certain images here (I think).</p><p>When developing, I skipped the wetting agent and just gave it a distilled water bath in the end, but I still ended up with some water droplet marks. So, I gave it another wash with Ilfotol.</p><br><p>Camera: Pentax P30T</p><p>Lens: Pentax SMC FA 1:4-5.6 35-80mm</p><p>Film stock: Kentmere 400</p><p>Developer: D76 (1+1) for 17 minutes (+1 Push - i.e., Shot as ISO 800) at 20°C</p>"
slug = "2023w48w49"
folder = "./content/2023w48w49/"
ascending = true


[[section]]
title = "2023 W47"
text = "I brewed some D76 using formula from digitaltruth.com <p/>Camera: Pentax P30T <p/> Film stock: Kentmere 400, shot at boxspeed <p/> Developer: D76 (1+1) for 12 minutes. <p/> I shot most of these by overexposing by one stop and reducing the development time by 15 %"
slug = "2023w47"
folder = "./content/2023w47/"
ascending = true

[[section]]
title = "2023 W46"
text = "Camera: Pentax P30T <p/> Film stock: Kentmere 400, shot at boxspeed <p/> Developer: Parodinal (1+50) for 17.5 minutes"
slug = "2023w46"
folder = "./content/2023w46/"
ascending = true

[[section]]
title = "2023 W45"
text = "Camera: Pentax P30T <p/> Film stock: Kentmere 400, shot at boxspeed <p/> Developer: Parodinal (1+50) for 13 minutes<p/> I overexposed most of these by 1 stop and then reduced the development time by 25%"
slug = "2023w45"
folder = "./content/belgaum_2023w45/"
ascending = true

[[section]]
title = "2023 W44"
text = "Camera: Pentax P30T <p/> Film stock: Kentmere 400, shot at boxspeed <p/> Developer: Parodinal (1+50) for 17.5 minutes<p/>"
slug = "2023w44"
folder = "./content/2023w44/"
ascending = true

[[section]]
title = "2023 W43"
text = "Camera: Pentax P30T <p/> Film stock: Kentmere 400, shot at boxspeed <p/> Developer: Parodinal (1+50) for 17.5 minutes<p/>"
slug = "2023w43"
folder = "./content/Kentmere_2023w43/"
ascending = true

[[section]]
title = "2023 W42"
text = "Camera: Pentax P30T <p/> Film stock: Fomapan 400, shot at boxspeed <p/> Developer: Parodinal (1+50) for 11 minutes<p/>"
slug = "2023w42"
folder = "./content/fomapan_2023w42/"
ascending = true

[[section]]
title = "2023 W41"
text = "Camera: Pentax P30T <p/> Film stock: Kentmere 400, shot at boxspeed <p/> Developer: Parodinal (1+25) for 7.5 minutes<p/>"
slug = "2023w41"
folder = "./content/2023w41/"
ascending = true

[[section]]
title = "2023 W40"
text = "Camera: Pentax P30T <p/> Film stock: Kentmere 400, shot at boxspeed <p/> Developer: Parodinal (1+50) for 17.5 minutes<p/>"
slug = "2023w40"
folder = "./content/2023w40/"
ascending = true


[[section]]
title = "2023 W39"
text = "I made Parodinal, an alternative developer made using Paracetamol and Sodium Hydroxide. Recipe from Digital Truth. <p/>Camera: Pentax P30T <p/> Film stock: Kentmere 400, shot at boxspeed <p/> Developer: Parodinal (1+50) for 17.5 minutes<p/>"
slug = "2023w39"
folder = "./content/parodinal_w39/"
ascending = true

[[section]]
title = "2023 W38"
text = "Shot a test roll with the new camera, Pentax P30T. Sent it to CPB Chennai for development. <p/> Camera: Pentax P30T <p/> Film stock: Kentmere 400, shot at boxspeed <p/> Developer: D76, developed by CPB Chennai<p/>"
slug = "2023w38"
folder = "./content/pentax_2023w38/"
ascending = true


[[section]]
title = "2023 W37"
text = "Workshop with Hellmuth Conz in Bangalore"
slug = "2023w37"
folder = "./content/hellmuth_2023w37/"
ascending = true

[[section]]
title = "Chennai_2"
text = "Day two of CPB Analog 101 workshop"
slug = "chennai_2"
folder = "./content/Chennai_2/"
ascending = true

[[section]]
title = "Chennai_1"
text = "Day one of CPB Analog 101 workshop"
slug = "chennai_1"
folder = "./content/Chennai_1/"
ascending = true



# Other setings
[others]
# Folders that should be copied together when exporting sites
folders = [ "assets", "media" ]
# Show `Generated by foto` footer or not
show_foto_footer = true
